from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from md_packages.materialize import (
    MaterializationError,
    apply_materialization,
    patch_agent_entrypoint,
    plan_materialization,
    recover_scope,
    sha256_bytes,
)
from md_packages.routing import RouteValidationError, render_router, render_router_extension
from md_packages.transaction import ScopeLocks, canonical_scope_paths
from md_packages.transaction import Journal


class MaterializationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)

    def tearDown(self) -> None:
        self.temp.cleanup()

    def test_router_is_deterministic_and_preserves_read_order(self) -> None:
        routes = {"z": {"when": "Z", "read": ["docs/second.md", "docs/first.md"]}, "a": {"read": ["skills/x"]}}
        artifacts = {"skills/x": {"target": "skills/x"}}
        first = render_router(routes, artifacts)
        self.assertEqual(first, render_router(routes, artifacts))
        self.assertLess(first.index(b"## a"), first.index(b"## z"))
        self.assertLess(first.index(b"docs/second.md"), first.index(b"docs/first.md"))
        self.assertIn(b"generated by mdpkg", render_router_extension({}, {}))

    def test_unknown_artifact_reference_fails(self) -> None:
        with self.assertRaises(RouteValidationError):
            render_router({"x": {"read": ["skills/missing"]}}, {"skills/known": "skills/known"})

    def test_entrypoint_preserves_outside_marked_block(self) -> None:
        original = b"# Personal\nBefore\n<!-- md:router:start -->\nold\n<!-- md:router:end -->\nAfter\n"
        patched = patch_agent_entrypoint(original)
        self.assertTrue(patched.startswith(b"# Personal\nBefore\n"))
        self.assertTrue(patched.endswith(b"After\n"))
        self.assertEqual(patched, patch_agent_entrypoint(patched))

    def test_unmanaged_and_modified_ownership_conflicts(self) -> None:
        (self.root / "ROUTER.md").write_text("mine")
        with self.assertRaises(MaterializationError):
            plan_materialization(self.root, {"ROUTER.md": "new"})
        (self.root / "ROUTER.md").write_text("managed")
        prior = {"outputs": {"ROUTER.md": {"sha256": sha256_bytes(b"managed")}}}
        (self.root / "ROUTER.md").write_text("changed")
        with self.assertRaises(MaterializationError):
            plan_materialization(self.root, {"ROUTER.md": "new"}, previous_lock=prior)

    def test_idempotency_and_safe_removal(self) -> None:
        plan = plan_materialization(self.root, {"ROUTER.md": "one"})
        apply_materialization(plan)
        again = plan_materialization(self.root, {"ROUTER.md": "one"})
        apply_materialization(again)
        self.assertEqual((self.root / "ROUTER.md").read_text(), "one")
        removed = plan_materialization(self.root, {})
        apply_materialization(removed)
        self.assertFalse((self.root / "ROUTER.md").exists())
        plan = plan_materialization(self.root, {"ROUTER.md": "one"})
        apply_materialization(plan)
        (self.root / "ROUTER.md").write_text("local")
        with self.assertRaises(MaterializationError):
            plan_materialization(self.root, {})

    def test_lock_metadata_is_preserved_but_output_hashes_are_materializer_owned(self) -> None:
        metadata = {
            "version": 7,
            "schemaVersion": 3,
            "routerRendererVersion": 2,
            "resolution": {"sources": [{"package": "@shared/base", "hash": "pin"}]},
            "artifacts": [{"identity": "skills/a", "hash": "content"}],
            "routes": [{"key": "a", "metadataHash": "route"}],
        }
        plan = plan_materialization(self.root, {"ROUTER.md": "router"}, lock_metadata=metadata)
        apply_materialization(plan)
        saved = json.loads((self.root / ".md-lock.json").read_text())
        self.assertEqual(saved["schemaVersion"], 3)
        self.assertEqual(saved["routerRendererVersion"], 2)
        self.assertEqual(saved["resolution"], metadata["resolution"])
        self.assertEqual(saved["outputs"], {"ROUTER.md": {"sha256": sha256_bytes(b"router"), "mode": 0o644}})
        with self.assertRaises(MaterializationError):
            plan_materialization(
                self.root,
                {"ROUTER.md": "router"},
                previous_lock=saved,
                lock_metadata={"outputs": {"ROUTER.md": {"sha256": "spoofed"}}},
            )
        # A caller may repeat the calculated value, but cannot own or alter it.
        allowed = plan_materialization(
            self.root,
            {"ROUTER.md": "router"},
            previous_lock=saved,
            lock_metadata={"outputs": saved["outputs"], "schemaVersion": 4},
        )
        self.assertEqual(allowed.lock["schemaVersion"], 4)

    def test_canonical_lock_order(self) -> None:
        a, b = self.root / "z", self.root / "a"
        self.assertEqual(canonical_scope_paths([a, b]), [b.resolve(), a.resolve()])
        with ScopeLocks([a, b]):
            self.assertTrue((a / ".md-install.lock").exists())
            self.assertTrue((b / ".md-install.lock").exists())
        self.assertFalse((a / ".md-install.lock").exists())

        acquired: list[Path] = []
        class RecordingScopeLocks(ScopeLocks):
            def acquire(self) -> "RecordingScopeLocks":
                acquired.extend(self.scopes)
                return super().acquire()

        plans = [plan_materialization(scope, {"ROUTER.md": scope.name}) for scope in (a, b)]
        with patch("md_packages.materialize.ScopeLocks", RecordingScopeLocks):
            apply_materialization(plans)
        self.assertEqual(acquired, [b.resolve(), a.resolve()])

    def test_later_stale_scope_leaves_earlier_scope_unchanged(self) -> None:
        first, second = self.root / "a", self.root / "z"
        first.mkdir()
        second.mkdir()
        apply_materialization([
            plan_materialization(first, {"ROUTER.md": "original first"}),
            plan_materialization(second, {"ROUTER.md": "original second"}),
        ])
        plans = [
            plan_materialization(first, {"ROUTER.md": "updated first"}),
            plan_materialization(second, {"ROUTER.md": "updated second"}),
        ]
        first_before = {
            path.relative_to(first): path.read_bytes()
            for path in first.rglob("*") if path.is_file()
        }
        second_lock = second / ".md-lock.json"
        stale_lock = json.loads(second_lock.read_text())
        stale_lock["externalChange"] = True
        second_lock.write_text(json.dumps(stale_lock))

        with self.assertRaisesRegex(MaterializationError, "plan is stale"):
            apply_materialization(plans)

        self.assertEqual(
            {path.relative_to(first): path.read_bytes() for path in first.rglob("*") if path.is_file()},
            first_before,
        )
        self.assertEqual((first / "ROUTER.md").read_text(), "original first")
        self.assertEqual((second / "ROUTER.md").read_text(), "original second")
        self.assertEqual(json.loads(second_lock.read_text()), stale_lock)
        self.assertFalse((first / ".md-install.lock").exists())
        self.assertFalse((second / ".md-install.lock").exists())

    def test_failure_rolls_back_and_lock_is_last(self) -> None:
        old = {"outputs": {"ROUTER.md": {"sha256": sha256_bytes(b"old")}}}
        (self.root / "ROUTER.md").write_text("old")
        (self.root / ".md-lock.json").write_text(json.dumps(old))
        plan = plan_materialization(self.root, {"ROUTER.md": "new", "router-extension.md": "extension"})
        seen_lock_states: list[bool] = []
        def fail(path: str) -> None:
            seen_lock_states.append((self.root / ".md-lock.json").exists())
            if path == "router-extension.md":
                raise RuntimeError("stop")
        with self.assertRaises(RuntimeError):
            apply_materialization(plan, failure_injector=fail)
        self.assertEqual((self.root / "ROUTER.md").read_text(), "old")
        self.assertFalse((self.root / "router-extension.md").exists())
        self.assertTrue(all(seen_lock_states))
        self.assertEqual(json.loads((self.root / ".md-lock.json").read_text()), old)
        self.assertEqual(recover_scope(self.root), [])

        fresh = self.root / "fresh"; fresh.mkdir()
        fresh_plan = plan_materialization(fresh, {"ROUTER.md": "new"})
        with self.assertRaises(RuntimeError):
            apply_materialization(fresh_plan, failure_injector=lambda _: (_ for _ in ()).throw(RuntimeError("stop")))
        self.assertFalse((fresh / ".md-lock.json").exists())

    def test_recovery_restores_an_interrupted_replacement(self) -> None:
        (self.root / "ROUTER.md").write_text("new")
        journal = Journal(self.root, "interrupted")
        backup = journal.directory / "backup" / "ROUTER.md"
        backup.parent.mkdir(parents=True, exist_ok=True)
        backup.write_text("old")
        journal.data["state"] = "staged"
        journal.data["operations"] = [{"path": "ROUTER.md", "backup": str(backup), "had_original": True}]
        journal.save()
        recovered = recover_scope(self.root)
        self.assertEqual(recovered, [journal.path])
        self.assertEqual((self.root / "ROUTER.md").read_text(), "old")
        self.assertEqual(json.loads(journal.path.read_text())["state"], "recovered")
        self.assertEqual(recover_scope(self.root), [])
        self.assertEqual((self.root / "ROUTER.md").read_text(), "old")

    def test_symlink_ancestors_never_write_or_remove_outside(self) -> None:
        scope, outside = self.root / "scope", self.root / "outside"
        scope.mkdir(); outside.mkdir()
        (scope / "docs").symlink_to(outside, target_is_directory=True)
        (outside / "guide.md").write_text("keep")
        for outputs, previous in (({"docs/new.md": "new"}, None),
                                  ({}, {"outputs": {"docs/guide.md": sha256_bytes(b"keep")}})):
            with self.assertRaisesRegex(ValueError, "symlink"):
                plan_materialization(scope, outputs, previous_lock=previous)
        self.assertEqual((outside / "guide.md").read_text(), "keep")
        self.assertFalse((outside / "new.md").exists())
        (scope / ".md").symlink_to(outside, target_is_directory=True)
        with self.assertRaisesRegex(ValueError, "symlink"):
            plan_materialization(scope, {"ROUTER.md": "new"})
        with self.assertRaisesRegex(ValueError, "symlink"):
            recover_scope(scope)

    def test_all_physical_overlaps_rejected_before_mutation(self) -> None:
        for parent_target in ("child/ROUTER.md", "child", "child/ROUTER.md/descendant"):
            with self.subTest(parent_target=parent_target):
                parent = self.root / str(len(parent_target))
                child = parent / "child"
                plans = [plan_materialization(parent, {parent_target: "parent"}),
                         plan_materialization(child, {"ROUTER.md": "child"})]
                with self.assertRaisesRegex(MaterializationError, "overlapping physical"):
                    apply_materialization(plans)
                self.assertFalse(parent.exists())

    def test_crash_at_every_replace_boundary_restores_outputs_and_old_lock(self) -> None:
        boundaries = [f"{prefix}{name}" for name in ("ROUTER.md", "obsolete.md", ".md-lock.json")
                      for prefix in ("intent:", "backup:", "")]
        for index, boundary in enumerate(boundaries):
            with self.subTest(boundary=boundary):
                root = self.root / str(index)
                root.mkdir()
                apply_materialization(plan_materialization(root, {"ROUTER.md": "old", "obsolete.md": "keep"}))
                lock = (root / ".md-lock.json").read_bytes()
                plan = plan_materialization(root, {"ROUTER.md": "new"})
                def crash(event: str) -> None:
                    if event == boundary:
                        raise KeyboardInterrupt("simulated process crash")
                with self.assertRaises(KeyboardInterrupt):
                    apply_materialization(plan, failure_injector=crash)
                self.assertEqual(len(recover_scope(root)), 1)
                self.assertEqual(recover_scope(root), [])
                self.assertEqual((root / "ROUTER.md").read_text(), "old")
                self.assertEqual((root / "obsolete.md").read_text(), "keep")
                self.assertEqual((root / ".md-lock.json").read_bytes(), lock)

    def test_failure_after_lock_replacement_restores_old_lock(self) -> None:
        apply_materialization(plan_materialization(self.root, {"ROUTER.md": "old"}))
        lock = (self.root / ".md-lock.json").read_bytes()
        def fail(event: str) -> None:
            if event == ".md-lock.json":
                raise RuntimeError("lock replaced")
        with self.assertRaises(RuntimeError):
            apply_materialization(plan_materialization(self.root, {"ROUTER.md": "new"}), failure_injector=fail)
        self.assertEqual((self.root / ".md-lock.json").read_bytes(), lock)
        self.assertEqual((self.root / "ROUTER.md").read_text(), "old")

    def test_crash_before_creating_new_nested_output_is_recoverable(self) -> None:
        def crash(event: str) -> None:
            if event == "intent:docs/new.md":
                raise KeyboardInterrupt("crash before parent exists")
        with self.assertRaises(KeyboardInterrupt):
            apply_materialization(plan_materialization(self.root, {"docs/new.md": "new"}), failure_injector=crash)
        self.assertEqual(len(recover_scope(self.root)), 1)
        self.assertEqual(recover_scope(self.root), [])
        self.assertFalse((self.root / "docs/new.md").exists())

    def test_legacy_string_hash_ownership_remains_compatible(self) -> None:
        (self.root / "old.md").write_text("old")
        (self.root / ".md-lock.json").write_text(json.dumps({"version": 1, "outputs": {"old.md": sha256_bytes(b"old")}}))
        apply_materialization(plan_materialization(self.root, {"old.md": "updated"}))
        self.assertEqual((self.root / "old.md").read_text(), "updated")


if __name__ == "__main__":
    unittest.main()
