"""Deterministic rendering for generated Markdown routing files.

The resolver deliberately does not live here.  These functions accept plain
JSON-shaped dictionaries so the renderer can be used by both the CLI and tests
without coupling its output to a particular resolver representation.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import PurePosixPath
from typing import Any


class RouteValidationError(ValueError):
    """A route points at an artifact which is not in the resolved view."""


def _as_routes(routes: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None) -> list[tuple[str, dict[str, Any]]]:
    if routes is None:
        return []
    if isinstance(routes, Mapping):
        result = [(str(key), dict(value)) for key, value in routes.items()]
    else:
        result = []
        for value in routes:
            if "key" not in value:
                raise RouteValidationError("route list entries require a key")
            result.append((str(value["key"]), dict(value)))
    keys = [key for key, _ in result]
    if len(keys) != len(set(keys)):
        raise RouteValidationError("duplicate route key")
    return sorted(result, key=lambda item: item[0])


def _artifact_targets(artifacts: Mapping[str, Any] | None) -> dict[str, str]:
    """Return ``kind/key -> target`` from a loose JSON-compatible artifact map."""
    result: dict[str, str] = {}
    for key, raw in (artifacts or {}).items():
        if isinstance(raw, str):
            target = raw
        elif isinstance(raw, Mapping):
            target = raw.get("target") or raw.get("path")
        else:
            raise RouteValidationError(f"artifact {key!r} has no target")
        if not isinstance(target, str):
            raise RouteValidationError(f"artifact {key!r} has no target")
        result[str(key)] = _safe_target(target, f"artifact {key!r}")
    return result


def _safe_target(target: str, label: str) -> str:
    path = PurePosixPath(target)
    if not target or path.is_absolute() or ".." in path.parts or str(path) == ".":
        raise RouteValidationError(f"{label} has unsafe target {target!r}")
    return path.as_posix()


def _read_target(reference: str, artifacts: Mapping[str, str]) -> str:
    # A slash-containing value is an artifact identity only when it is known.
    # Otherwise it is a controlled, repository-relative local document target.
    if reference in artifacts:
        return artifacts[reference]
    return _safe_target(reference, f"route read reference {reference!r}")


def validate_routes(
    routes: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None,
    artifacts: Mapping[str, Any] | None = None,
) -> list[tuple[str, dict[str, Any], list[str]]]:
    """Validate and normalize routes, preserving each declaration's read order.

    Unknown strings which look like package artifact references (``kind/key``)
    are rejected when a non-empty artifact view is supplied.  Plain repository
    local documents remain supported controlled targets.
    """
    targets = _artifact_targets(artifacts)
    validated: list[tuple[str, dict[str, Any], list[str]]] = []
    for key, route in _as_routes(routes):
        if route.get("disabled") is True:
            continue
        reads = route.get("read", [])
        if not isinstance(reads, list) or not all(isinstance(item, str) for item in reads):
            raise RouteValidationError(f"route {key!r} read must be an array of strings")
        rendered: list[str] = []
        for reference in reads:
            if reference in targets:
                rendered.append(targets[reference])
                continue
            # Artifact-shaped references are almost certainly a typo, while
            # docs/foo.md is a legitimate repository-relative local document.
            if "/" in reference and not reference.endswith(".md"):
                raise RouteValidationError(f"route {key!r} references unknown artifact {reference!r}")
            rendered.append(_read_target(reference, targets))
        validated.append((key, route, rendered))
    return validated


def _render(title: str, routes: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None, artifacts: Mapping[str, Any] | None) -> str:
    lines = [
        "<!-- generated by mdpkg; do not edit -->",
        f"# {title}",
        "",
    ]
    for key, route, reads in validate_routes(routes, artifacts):
        lines.append(f"## {key}")
        when = route.get("when")
        if isinstance(when, str) and when:
            lines.extend(["", when])
        if reads:
            lines.extend(["", "Read:"])
            # This is intentionally not sorted: declaration order can express
            # an instruction sequence.
            lines.extend(f"- [{target}]({target})" for target in reads)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_router_extension(
    scope_routes: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None,
    artifacts: Mapping[str, Any] | None = None,
) -> bytes:
    """Render a scope-local ``router-extension.md`` deterministically."""
    return _render("Scope router extension", scope_routes, artifacts).encode("utf-8")


def render_router(
    effective_routes: Mapping[str, Any] | Sequence[Mapping[str, Any]] | None,
    artifacts: Mapping[str, Any] | None = None,
) -> bytes:
    """Render the effective ``ROUTER.md`` deterministically."""
    return _render("Router", effective_routes, artifacts).encode("utf-8")
